server:
  port: 8080
  servlet:
    context-path: /chatapp

spring:
  jpa:
    hibernate:
      naming: #tắt tự động đổi tên trong entity
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    url: "jdbc:mysql://localhost:3306/chatapp"
    username: root
    password: vrain2403

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

jwt:
  signerKey: "cm/Gq7l0JEeYl+VIjShBpiS/ko0DxckvG0uHK2o7c55GNIeWjJy70m57vGCgib4q"


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
    root: INFO

cloudinary:
  cloud-name: "dcrsia5sh"
  api-key: 362629979878447
  api-secret: meHypXTNOINYjJ8jXQ6q-qYEdPM
